In [1]:
import cv2
import numpy as np

In [9]:
img= cv2.imread(r"C:\Users\kamal\Downloads\Data Files for Python\Test\Beatles.jpg",1)# 1 is for coloured image, use r at starting
img1= cv2.imread(r"C:\Users\kamal\Downloads\Data Files for Python\Test\Beatles.jpg",0)# 1 is for coloured image, use r at starting

#print(img)
img.shape # checking size of image, a no. 3 will come in last for coloured image
img1.shape[0:] # a tuple of pixel values is retuned

(183, 275)

In [10]:
img1

array([[243, 243, 242, ...,  31,  31,  31],
       [243, 242, 242, ...,  31,  31,  31],
       [242, 242, 242, ...,  30,  30,  30],
       ...,
       [151, 152, 152, ...,  42,  41,  49],
       [153, 153, 154, ...,  46,  42,  39],
       [154, 154, 155, ...,  37,  36,  32]], dtype=uint8)

In [11]:
#Image display

cv2.imshow("bharat",img)#display of image

cv2.waitKey(0)#closes the image window with any click for 0, for  any other number for given milliseconds
cv2.destroyAllWindows()

In [14]:
#Resize image

resize=cv2.resize(img,(300,300))

cv2.imshow("",resize)
cv2.waitKey(20000)
cv2.destroyAllWindows()

In [ ]:
#haar classifier

#cascade classifier-read more
facec=cv2.CascadeClassifier(r"C:\Users\kamal\Downloads\Data Files for Python\Harcascade Docs\haarcascade_frontalface_default.xml")
faces=facec.detectMultiScale(img, scaleFactor=1.05 , minNeighbors=5,minSize=(30,30))
print(faces)

for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y), (x+w,y+h),(255,0,0),3 )

cv2.imshow("faces",img)

cv2.waitKey(0)
cv2.destroyAllWindows()


[[235  34  32  32]
 [152  39  34  34]
 [206  38  33  33]]
